export default function Home() {
  return (
    <main style={{ padding: '2rem', maxWidth: 960, margin: '0 auto' }}>
      <h1>cafe website 3d animation name Ayaan caf</h1>
      <p>Welcome! This site was generated by Heaven AI Engine.</p>
    </main>
  );
}
